CREATE TABLE IF NOT EXISTS user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  organization VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_email (email)
);

CREATE TABLE IF NOT EXISTS formation (
  id INT NOT NULL AUTO_INCREMENT,
  titre VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  datePubli DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  imageUrl TEXT,
  PRIMARY KEY (id)
);
